@ECHO OFF
IF NOT "%1"=="AM_ADMIN" (POWERSHELL START -VERB RUNAS '%0' AM_ADMIN & EXIT /B)
TITLE BUILDBOT - FINASTRA
@ECHO OFF
CLS
COLOR 2
ECHO.
ECHO ******** BUILDBOT V1 **********
ECHO.

:VARIABLE SETUP
SET STARTTIME=%TIME%
SET BUILDBOTFOLDER=%USERPROFILE%\Desktop\BUILDBOT
IF NOT EXIST %BUILDBOTFOLDER% (
ECHO BuildBOT folder not found!
MD %BUILDBOTFOLDER%
MD %BUILDBOTFOLDER%\Configs
MD %BUILDBOTFOLDER%\Builds
ECHO Folder created successfully at "%BUILDBOTFOLDER%"
ECHO.
)
IF NOT EXIST %BUILDBOTFOLDER%\Configs (
ECHO Configuration folder not found!
MD %BUILDBOTFOLDER%\Configs
MD %BUILDBOTFOLDER%\Builds
ECHO Folder created successfully at "%BUILDBOTFOLDER%\Configs"
ECHO.
)
IF NOT EXIST %BUILDBOTFOLDER%\Builds (
ECHO Builds folder not found!
MD %BUILDBOTFOLDER%\Builds
ECHO Folder created successfully at "%BUILDBOTFOLDER%\Builds"
ECHO.
)
SET BUILDCONFIG=%BUILDBOTFOLDER%\Configs\BuildBOT.config
IF NOT EXIST %BUILDCONFIG% (
ECHO Build configuration not found!
ECHO BuildBOT Configuration File>%BUILDCONFIG%
ECHO.>>%BUILDCONFIG%
ECHO dcpversion='19.1'>>%BUILDCONFIG%
ECHO buildversion='DCP_Installs_20181223223412.94'>>%BUILDCONFIG%
ECHO Configuration file created successfully at "%BUILDCONFIG%"
ECHO.
ECHO Please enter the DCP version inside the configuration file "Example: 19.1"
PAUSE > NUL
EXIT
)
SET DEVINSTALLSFOLDER="\\10.149.228.39\Code Build\_DEV_Installs"
SET DCPCURRENTBUILDFOLDER="C:\Program Files (x86)\DH\DCP_Current_Build"
SET DCPFOLDER="C:\Program Files (x86)\DH\DCP"

:READ CONFIGURATION FILE
SETLOCAL ENABLEDELAYEDEXPANSION
SET I=0
FOR /F "TOKENS=2 DELIMS='" %%A IN (%BUILDCONFIG%) DO (
  SET /A I+=1
  SET DRIVE[!I!]=%%A
)
SET DCPVERSION=%DRIVE[1]%
SET BUILDVERSION=%DRIVE[2]%

IF %DCPVERSION%==unavailable (
ECHO  Please enter the DCP version inside the configuration file "Example: 19.1"
PAUSE > NUL
EXIT
)
SET BUILDLOG=%BUILDBOTFOLDER%\Builds\%BUILDVERSION%\%BUILDVERSION%.log
REM :CHECKING FOR NEW BUILD
REM ECHO Checking for new build...
REM FOR /F "DELIMS=" %%i IN ('DIR %DEVINSTALLSFOLDER% /B /OD') DO SET LATESTBUILDFOLDER=%%i
REM FOR /F "DELIMS=" %%i IN ('DIR %DEVINSTALLSFOLDER%\%LATESTBUILDFOLDER%\*.zip /B /O:D') DO SET LATESTBUILDARCHIVE=%%i
REM FOR /F "TOKENS=1,2,3 DELIMS=." %%A IN ("%LATESTBUILDARCHIVE%") DO SET LATESTVERSION=%%A.%%B
REM ECHO Current version: %BUILDVERSION%
REM ECHO Latest Version: %LATESTVERSION%
REM IF %BUILDVERSION%==%LATESTVERSION% (
REM ECHO You are already on latest build: %LATESTVERSION% 
REM PAUSE > NUL
REM EXIT
REM )
REM ECHO.
REM IF %BUILDVERSION%==unavailable SET BUILDVERSION=%LATESTVERSION%
REM SET CURRENTBUILDFOLDER=%BUILDBOTFOLDER%\Builds\%BUILDVERSION%
REM IF NOT EXIST %CURRENTBUILDFOLDER% MD %CURRENTBUILDFOLDER%
REM SET BUILDLOG=%CURRENTBUILDFOLDER%\%BUILDVERSION%.log
REM ECHO.>%BUILDLOG%
REM CALL:LOG "***********************************************************"
REM CALL:LOG "A new build is available: %LATESTVERSION%"
REM CALL:LOG "Build update started at %STARTTIME%"
REM CALL:LOG "***********************************************************"
REM CALL:NEWLINE

REM :COPY LATEST BUILD TO LOCAL
REM IF EXIST %CURRENTBUILDFOLDER%\%LATESTBUILDARCHIVE% (
REM DEL %CURRENTBUILDFOLDER%\%LATESTBUILDARCHIVE%
REM CALL:LOG "File named %LATESTBUILDARCHIVE% exist. Deleting the old file.."
REM )
REM CALL:LOG "Copying the latest build to %CURRENTBUILDFOLDER%..."
REM ECHO.
REM COPY %DEVINSTALLSFOLDER%\%LATESTBUILDFOLDER%\%LATESTBUILDARCHIVE% %CURRENTBUILDFOLDER%\%LATESTBUILDARCHIVE% /Y /Z
REM IF %ERRORLEVEL%==0 (
REM CALL:LOG "File copy completed at %TIME%."
REM CALL:NEWLINE
REM ) ELSE (
REM CALL:LOG "File copy Failed."
REM PAUSE > NUL
REM EXIT
REM )

REM :DELETE DCP CURRENT BUILD FOLDER
REM CALL:LOG "Deleting "DCP_Current_Build" folder..."
REM IF EXIST %DCPCURRENTBUILDFOLDER% (
REM RMDIR /S /Q %DCPCURRENTBUILDFOLDER%
REM )
REM MD %DCPCURRENTBUILDFOLDER%
REM CALL:LOG "Deletion completed at %TIME%."
REM CALL:NEWLINE
REM PAUSE

REM :EXTRACT BUILD TO DCP CURRENT BUILD FOLDER
REM CALL:LOG "Extracting %LATESTBUILDARCHIVE% to %DCPCURRENTBUILDFOLDER%..."
REM IF EXIST %DCPCURRENTBUILDFOLDER% RMDIR /S /Q %DCPCURRENTBUILDFOLDER%
REM POWERSHELL.EXE -EXECUTIONPOLICY BYPASS -COMMAND EXPAND-ARCHIVE "%CURRENTBUILDFOLDER%\%LATESTBUILDARCHIVE%" "%DCPCURRENTBUILDFOLDER%"
REM CALL:LOG "Build extraction completed at %TIME%."
REM CALL:NEWLINE

REM :DELETE DCP FOLDER
REM CALL:LOG "Deleting DCP folder..."
REM FOR /D %%i IN (%DCPFOLDER%\*) DO (
REM IF NOT %%~ni==BACKUP (
REM IF NOT %%~ni==Backup (
REM IF NOT %%~ni==CONFIGS (
REM IF NOT %%~ni==Configs (
REM RMDIR /s /q %DCPFOLDER%\"%%~ni"
REM CALL:LOG   "* %%~ni folder deleted."
REM )))))
REM CALL:LOG "Deletion completed at %TIME%."
REM CALL:NEWLINE

:UNINSTALL DCP
CALL:LOG "Initiating DecisionPro Uninstallation..."
ECHO DecisionPro %DCPVERSION%
PAUSE
wmic product where name='DecisionPro %DCPVERSION%' call uninstall /nointeractive
CALL:LOG "Uninstallation completed at %TIME%."
CALL:NEWLINE

REM :INSTALL LATEST DCP
REM CALL:LOG "Initiating DecisionPro Installation..."
REM START "${Env:ProgramFiles(x86)}\DH\DCP_Current_Build\Consolidated\setup.exe"


SET ENDTIME=%TIME%
REM CHANGE FORMATTING FOR THE START AND END TIMES
FOR /F "TOKENS=1-4 DELIMS=:.," %%A IN ("%STARTTIME%") DO (
   SET /A "START=(((%%A*60)+1%%B %% 100)*60+1%%C %% 100)*100+1%%D %% 100"
)
FOR /F "TOKENS=1-4 DELIMS=:.," %%A IN ("%ENDTIME%") DO (
   SET /A "END=(((%%A*60)+1%%B %% 100)*60+1%%C %% 100)*100+1%%D %% 100"
)
REM CALCULATE THE ELAPSED TIME BY SUBTRACTING VALUES
SET /A ELAPSED=%END%-%START%

REM FORMAT THE RESULTS FOR OUTPUT
SET /A HH=ELAPSED/(60*60*100), REST=ELAPSED%%(60*60*100), MM=REST/(60*100), REST%%=60*100, SS=REST/100, CC=REST%%100
IF %HH% LSS 10 SET HH=0%HH%
IF %MM% LSS 10 SET MM=0%MM%
IF %SS% LSS 10 SET SS=0%SS%
IF %CC% LSS 10 SET CC=0%CC%
SET DURATION=%HH% hours %MM% minutes %SS% seconds %CC% microseconds
CALL:NEWLINE
CALL:LOG "Build update started at %STARTTIME%"
CALL:LOG "Build update ended at %ENDTIME%"
CALL:LOG "Total time taken: %DURATION%"

:LOG
ECHO %~1
ECHO %~1>>%BUILDLOG%
GOTO:EOF

:NEWLINE
ECHO.
ECHO.>>%BUILDLOG%
GOTO:EOF

PAUSE


REM NOTES
REM wmic product where name="DecisionPro 19.1" call uninstall /nointeractive
REM POWERSHELL.EXE  -EXECUTIONPOLICY BYPASS -FILE %~dp0\Uninstall.ps1 
REM wmic service where "NAME LIKE 'DsSvc%%'" CALL startservice > NUL

	REM SET DEVINSTALLSFOLDER=%USERPROFILE%
	REM SET LATESTBUILDFOLDER=Desktop
	REM SET LATESTBUILDARCHIVE=DCP_Installs_20181210224442.82.zip
	REM SET DCPCURRENTBUILDFOLDER="C:\Program Files (x86)\DH\DCP_Current_Build"
	REM SET DCPFOLDER="C:\Program Files (x86)\DH\DCP"
	REM IF NOT EXIST %BUILDBOTFOLDER% (
	REM ECHO BuildBOT folder not found!
	REM MD %BUILDBOTFOLDER%
	REM ECHO Folder created successfully ( %BUILDBOTFOLDER% )
	REM )
	REM SET BUILDCONFIG=%BUILDBOTFOLDER%\BuildBOT.config
	REM IF NOT EXIST %BUILDCONFIG% (
	REM ECHO Build configuration not found!
	REM ECHO unavailable>%BUILDCONFIG%
	REM ECHO Configuration file created successfully ( %BUILDCONFIG% )
	REM )

